[package]
name = "big_fluffy_dise"
version = "0.1.0"
authors = ["stuart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

digest = "0.9"
blake3 = "0.3"
sha3 = "0.9"

[dev-dependencies]